In [1]:
import pandas as pd

In [14]:
new_df = pd.read_csv("../data/processed/non_gt_outputs/batch_260226/260226_postproc.csv", encoding="utf-8-sig", skiprows=3, header=None)
old_df = pd.read_csv("../data/processed/non_gt_outputs/batch_260130/260130_postproc.csv", encoding="utf-8-sig", skiprows=3, header=None)

In [15]:
old_df.shape

(32, 96)

In [16]:
new_df.shape

(32, 96)

In [17]:
new_df.head()

,0,1,2,3,4,5,6,7,8,9,...,86,87,88,89,90,91,92,93,94,95
0,Barzanji Makna Bugis,1896,14519.b.42,NaN,NaN,s,1896.0,NaN,si,0,...,NaN,NaN,NaN,NaN,NaN,NaN,legal deposit,NaN,NaN,1314 [June 1896-June 1897]
1,Barzanji Makna Bugis,1896†,NaN,NaN,NaN,s,NaN,NaN,si,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7 December 1896 (publication); 16 November 189...
2,Kaifiyat Khatam Quran,1294,NaN,NaN,NaN,s,1294.0,NaN,si,0,...,NaN,NaN,NaN,NaN,NaN,NaN,purchased,NaN,NaN,NaN
3,Kaifiyat Khatam Quran,1891,14620.f.3(1),NaN,NaN,s,1891.0,NaN,si,0,...,NaN,NaN,NaN,NaN,NaN,NaN,legal deposit,NaN,NaN,18 Sya'ban 130[8] [March 1891] :col\nwith 13 l...
4,Kaifiyat Khatam Quran,1891†,NaN,NaN,NaN,s,NaN,NaN,si,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27 June 1891 (publication); 8 June 1891 (print...

In [18]:
old_df.head()

,0,1,2,3,4,5,6,7,8,9,...,86,87,88,89,90,91,92,93,94,95
0,Barzanji Makna Bugis,1896,14519.b.42,NaN,NaN,s,1896.0,NaN,si,0,...,NaN,NaN,NaN,NaN,NaN,NaN,legal deposit,NaN,NaN,1314 [June 1896-June 1897]
1,Barzanji Makna Bugis,1896†,NaN,NaN,NaN,s,NaN,NaN,si,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7 December 1896 (publication); 16 November 189...
2,Kaifiyat Khatam Quran,a,NaN,NaN,NaN,s,NaN,NaN,si,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1294 [January 1877-January 1878]
3,Kaifiyat Khatam Quran,1891,14620.f.3(1),NaN,NaN,s,1891.0,NaN,si,0,...,NaN,NaN,NaN,NaN,NaN,NaN,legal deposit,NaN,NaN,18 Sya'ban 130[8] [March 1891] :col
4,Kaifiyat Khatam Quran,1891†,NaN,NaN,NaN,s,NaN,NaN,si,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27 June 1891 (publication); 8 June 1891 (print...